/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public interface tinyWRAPConstants {
  int tsip_event_code_dialog_transport_error = 702;
  int tsip_event_code_dialog_global_error = 703;
  int tsip_event_code_dialog_message_error = 704;
  int tsip_event_code_dialog_request_incoming = 800;
  int tsip_event_code_dialog_request_outgoing = 802;
  int tsip_event_code_dialog_request_cancelled = 803;
  int tsip_event_code_dialog_request_sent = 804;
  int tsip_event_code_dialog_request_prechecking = 805;
  int tsip_event_code_dialog_connecting = 900;
  int tsip_event_code_dialog_connected = 901;
  int tsip_event_code_dialog_terminating = 902;
  int tsip_event_code_dialog_terminated = 903;
  int tsip_event_code_stack_starting = 950;
  int tsip_event_code_stack_started = 951;
  int tsip_event_code_stack_stopping = 952;
  int tsip_event_code_stack_stopped = 953;
  int tsip_event_code_stack_failed_to_start = 954;
  int tsip_event_code_stack_failed_to_stop = 955;
  int tsip_event_code_stack_disconnected = 956;
}
